// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exit() {
  return window['go']['main']['App']['Exit']();
}

export function GetLiterature() {
  return window['go']['main']['App']['GetLiterature']();
}

export function OpenPDF(arg1) {
  return window['go']['main']['App']['OpenPDF'](arg1);
}
