// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exit():Promise<void>;

export function GetLiterature():Promise<Array<Record<string, string>>>;

export function OpenPDF(arg1:string):Promise<void>;
